#only asyncapi yml as input
#name: Messages code generation with AsyncAPI CLI
#
#on:
#  push:
#    branches:
#      - 'message-schema-generation'
##    paths:
##      - 'message-schema/**'
##      - '!**/*.md'
#
#jobs:
#  generate:
#    name: 'Generate messages'
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Setup .NET Core
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: 7.0.x
#
#      - name: Setup Node.js 16
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18
#      - name: Install AsyncAPI CLI
#        run: npm i -g @asyncapi/cli
#
#      - name: Create generated directory for message-schema
#        run: |
#          mkdir message-schema/generated
#          mkdir message-schema/generated/asyncapi
#          
#      - name: Generate C# Definitions
#        run: |
#          cd message-schema
#          rm -rf generated/asyncapi/csharp
#          mkdir generated/asyncapi/csharp
#          cd generated/asyncapi/csharp
#          dotnet new classlib -n JustJoinIt.Services.CandidateProfile.Contracts.Messages.Events --no-restore
#          rm JustJoinIt.Services.CandidateProfile.Contracts.Messages.Events/Class1.cs
#          asyncapi generate models csharp candidate-profile-created-event-v1.json -o JustJoinIt.Services.CandidateProfile.Contracts.Messages.Events/CandidateProfileExternalEvents.cs --namespace JustJoinIt.Services.CandidateProfile.Contracts.Messages.Events
#          cd JustJoinIt.Services.CandidateProfile.Contracts.Messages.Events
##          dotnet tool install dotnet-version-cli -g
##          dotnet version --skip-vcs 0.0.1
#
#      - name: Generate TypeScript Definitions
#        run: |
#          cd message-schema
#          rm -rf generated/asyncapi/typescript
#          mkdir generated/asyncapi/typescript
#          cd generated/asyncapi/typescript
#          asyncapi -s schema ../../../*.json -o candidateprofile-external-events.ts --just-types --acronym-style original --nice-property-names --explicit-unions --prefer-types
#
#      - name: Git add, commit, and push
#        run: |
#          git config user.name 'github-actions[bot]'
#          git config user.email 'github-actions[bot]@users.noreply.github.com'
#          git add .
#          git commit -m '✉️ messages: upgrade external messages (events and commands) definitions to version x.y.z'
#          git push
